version: '3.4'
services:
  hub:
    image: selenium/hub:2.53.0
    ports:
      - "4444:4444"
    networks:
      - selenium
    environment:
      - JAVA_OPTS=-Xmx1024m
  ff:
    image: sbower/node-firefox:2.53.0
    networks:
      - selenium
    links:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
networks:
  selenium:
    driver: overlay
    attachable: true
    ipam:
      config:
        - subnet: 10.0.0.0/24
